server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mlm
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      port: 8090

  mail:
    host: mail.amanatpay.com
    port: 587
    username: admin@amanatpay.com
    password: 2300479435Reza00!


encryption:
  key: d5s4a6d4a65d4sa6a554f6as
  salt: 54dfasfd4as5df4as64da6546a4d6
