server:
  port: 8082
  error:
    path: /custom-error
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mlm
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      port: 8090
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  mail:
    host: mail.amanatpay.com
    port: 587
    username: admin@amanatpay.com
    password: 2300479435Reza00!
  redis:
    host: localhost
    port: 6379

encryption:
  key: d5s4a6d4a65d4sa6a554f6as
  salt: 54dfasfd4as5df4as64da6546a4d6

WithdrawLowLimit: 30.00
WithdrawHighLimit: 1000.00

tronApiAdress: https://tronapi.coinnich.com/api/tron
