server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mlm
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      port: 8090

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_email_password


